name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: self-hosted
    #runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

#    - name: Setup Ruby
#      uses: ruby/setup-ruby@v1
#      with:
#        ruby-version: 3.1.0
#        bundler-cache: true
#      env:
#        ImageOS: macos1015

    - name: Setup Pods Cache
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: CocoaPod Install
      working-directory: ./Example
      run: pod install

    - name: Build and test with Fastlane
      working-directory: ./
      run: bundle exec fastlane tests
      
    #- name: Build
      #run: swift build -v
    #- name: Run tests
      #run: swift test -v
